### ISSUE TITLE
Don't have a product spec for: 'omni_rpi4'

### ISSUE THREAD

**Issue by arcadeperfect** [omnirom/android_device_brcm_rpi4#1]
Hi,
When trying to build I get the following:
```
In file included from build/make/core/config.mk:291:
In file included from build/make/core/envsetup.mk:266:
build/make/core/product_config.mk:155: error: Can not locate config makefile for product "omni_rpi4".
23:38:04 dumpvars failed with: exit status 1
Your device can't be found in device sources..
found the rpi4 device repo
syncing the device config
fatal: remote omnirom2 not defined in /home/alex/android_building/1/.repo/manifest.xml
Your device can't be found in device sources..
Traceback (most recent call last):
  File "vendor/omni/build/tools/roomservice.py", line 418, in <module>
    fetch_dependencies(device)
  File "vendor/omni/build/tools/roomservice.py", line 366, in fetch_dependencies
    raise Exception("ERROR: could not find your device "
Exception: ERROR: could not find your device folder location, bailing out
In file included from build/make/core/config.mk:291:
In file included from build/make/core/envsetup.mk:266:
build/make/core/product_config.mk:155: error: Can not locate config makefile for product "omni_rpi4".
23:38:05 dumpvars failed with: exit status 1

** Don't have a product spec for: 'omni_rpi4'
** Do you have the right repo manifest?
```

Any chance you can point me in the right direction?

**Comment by arcadeperfect** [comment]
PS this is the contents of my 'manifests' directory:
```
-rw-rw-r-- 1 alex alex 80144 Jan 28 20:48 default.xml
-rw-rw-r-- 1 alex alex   851 Jan 28 20:48 GLOBAL-PREUPLOAD.cfg
-rw-rw-r-- 1 alex alex  9505 Jan 28 20:48 omni-aosp.xml
-rw-rw-r-- 1 alex alex   936 Jan 28 20:48 omni-caf.xml
-rw-rw-r-- 1 alex alex  2579 Jan 28 21:39 omni-default.xml
-rw-rw-r-- 1 alex alex   564 Jan 28 20:48 omni-extra.xml
-rw-rw-r-- 1 alex alex  1096 Jan 28 20:48 omni-private.xml
-rw-rw-r-- 1 alex alex  3729 Jan 28 20:48 README.md
-rw-rw-r-- 1 alex alex  8447 Jan 28 20:48 remove.xml
```

**Comment by danialbehzadi** [comment]
Did you manage to fix this?

**Comment by arcadeperfect** [comment]
Yes, I had to get invited to the omni rpi4 GitHub project and set up an SSH
key. This allowed the breakfast (I think) command to fix some things and
sync that spec.

**Comment by danialbehzadi** [comment]
Okay.

For everyone else facing this issue, you can change the `default_rem` and `default_team_rem` in `build/tools/roomservice.py` from `omnirom2` to `omnirom`.
You may want to remove the `roomservice.xml` file before running `breakfast rpi4 userdebug` again.
